# API-based Configuration file for vm_autoscale
# Uses native Proxmox API instead of SSH commands
# Environment variables for sensitive data

# Global thresholds for scaling VMs
scaling_thresholds:
  cpu:
    high: 80            # Percentage CPU usage at which scaling up is triggered
    low: 20             # Percentage CPU usage at which scaling down is considered
  ram:
    high: 85            # Percentage RAM usage at which scaling up is triggered
    low: 25             # Percentage RAM usage at which scaling down is considered

# Scaling limits for VMs
scaling_limits:
  min_cores: 1          # Minimum number of CPU cores that a VM can have
  max_cores: 8          # Maximum number of CPU cores that a VM can have
  min_ram_mb: 1024      # Minimum RAM (in MB) that a VM can have
  max_ram_mb: 16384     # Maximum RAM (in MB) that a VM can have

# Time intervals for checking VM resources and performing actions (in seconds)
check_interval: 300      # How often to check VM stats and take action if needed
scale_cooldown: 300      # Cooldown between scaling operations for the same VM

# List of Proxmox hosts to manage via API
proxmox_hosts:
  # Example with username/password authentication
  - name: host1
    host: 192.168.1.10
    api_port: 8006                                    # Proxmox API port (default 8006)
    api_username: root@pam                           # API username with realm
    api_password: ${PROXMOX_HOST1_API_PASSWORD}      # From environment variable
    verify_ssl: true                                 # Verify SSL certificates
    # ca_cert_path: /path/to/ca.crt                  # Optional: custom CA certificate
    node_name: proxmox-node1                         # Specific node name (for single node)
    auto_discover_nodes: false                       # Auto-discover cluster nodes
    timeout: 30                                      # API request timeout
    max_retries: 3                                   # Maximum retry attempts

  # Example with API token authentication
  - name: host2
    host: 192.168.1.11
    api_port: 8006
    api_token_id: ${PROXMOX_HOST2_API_TOKEN_ID}      # From environment variable
    api_token_secret: ${PROXMOX_HOST2_API_TOKEN_SECRET}  # From environment variable
    verify_ssl: true
    node_name: proxmox-node2
    auto_discover_nodes: false
    timeout: 30
    max_retries: 3

  # Example cluster configuration with auto-discovery
  - name: cluster1
    host: 192.168.1.20                              # Any cluster node IP
    api_port: 8006
    api_username: root@pam
    api_password: ${PROXMOX_CLUSTER_API_PASSWORD}
    verify_ssl: false                               # Allow self-signed certificates
    auto_discover_nodes: true                       # Auto-discover all cluster nodes
    timeout: 45                                     # Longer timeout for cluster operations
    max_retries: 5

# Virtual machines to be monitored and scaled
virtual_machines:
  - vm_id: 101
    proxmox_host: host1
    scaling_enabled: true
    cpu_scaling: true    # Enable/disable CPU scaling
    ram_scaling: true    # Enable/disable RAM scaling

  - vm_id: 102
    proxmox_host: host2
    scaling_enabled: true
    cpu_scaling: true
    ram_scaling: true

  - vm_id: 201
    proxmox_host: cluster1
    scaling_enabled: true
    cpu_scaling: true
    ram_scaling: false   # Only CPU scaling for this VM

# Logging configuration
logging:
  level: INFO                         # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  log_file: /var/log/vm_autoscale_api.log # Path to the log file

# Email alerts configuration (Optional)
alerts:
  email_enabled: false                      # Set to true to enable email notifications
  email_recipient: admin@example.com       # Email recipient
  smtp_server: smtp.example.com            # SMTP server
  smtp_port: 587                           # SMTP port
  smtp_user: your_smtp_user                # SMTP username
  smtp_password: ${SMTP_PASSWORD}          # SMTP password from environment variable

# Gotify notifications configuration (Optional)
gotify:
  enabled: false                                    # Set to true to enable Gotify notifications
  server_url: https://gotify.example.com           # Base URL of the Gotify server
  app_token: ${GOTIFY_APP_TOKEN}                   # Application token from environment variable
  priority: 5                                       # Notification priority level (1-10)

# Safety checks for host resource limits
host_limits:
  max_host_cpu_percent: 90            # Max CPU usage percentage for the host before scaling is restricted
  max_host_ram_percent: 90            # Max RAM usage percentage for the host before scaling is restricted